### ISSUE TITLE
What is target of this project?

### ISSUE THREAD

**Issue by olljanat** [fortinet/k8s-fortigate-ctrl#2]
This is very interesting tool sample for existing Fortigate users who are looking to start implementing Kubernetes environment(s).

However I have trouble to understand that what is target of this project? For me it looks like that this one has been made as example for some customer/etc but has someone created improved version of it and/or is plan that this will be improved in future?

I can contribute to improve this one but it would be nice if someone can first tell more about background and fix those hardcoding from code.

**Comment by thomnico** [comment]
Hello,

You understood the idea of a proven prototype and associated demo: check here http://secured-aks-reference-architecture.rtfd.io/ 

I am no longer working on this, so please reach out to your Fortinet rep to discuss options.

Hope this helps,
